### ISSUE TITLE
Can you share the code of the whole experiment？

### ISSUE THREAD

**Issue by fengzhi6** [ShuyueG/GAN_evaluation_LS#1]
Can you share the code of the whole experiment？

**Comment by ShuyueG** [comment]
The code of the whole experiment needs to be more organized to share. Except for the code of our proposed LS (DSI), other codes, such as for calculating IS and training the DCGAN model, can be easily found online. Our paper also provides the source links for the codes and datasets we used. Thank you.

**Comment by ShuyueG** [comment]
The code of the whole experiment needs to be more organized to share. Except for the code of our proposed LS (DSI), other codes, such as for calculating IS and training the DCGAN model, can be easily found online. Our paper also provides the source links for the codes and datasets we used. Thank you.
